blank_issues_enabled: false
contact_links:
  - name: Liferay Issues
    url: https://issues.liferay.com/secure/CreateIssue.jspa
    about: 'Please use Liferay issues platform to report bugs or feature requests (use project "PUBLIC - Liferay Portal Community Edition" and component "Fragments Toolkit").'
