import execa from 'execa';
import voca from 'voca';

import CollectionGenerator from '../collection';
import {
  COLLECTION_DESCRIPTION_VAR,
  COLLECTION_NAME_VAR,
  FRAGMENT_COLLECTION_SLUG_VAR,
  FRAGMENT_NAME_VAR,
  FRAGMENT_TYPE_VAR,
  USE_DATA_LFR_EDITABLES_VAR,
} from '../utils/constants';
import CustomGenerator from '../utils/custom-generator';

const ADD_SAMPLE_CONTENT_VAR = 'addSampleContent';
const PROJECT_NAME_VAR = 'projectName';
const PROJECT_SLUG_VAR = 'projectSlug';

export default class AppGenerator extends CustomGenerator {
  async prompting(): Promise<void> {
    this.log(`
    __    ____________________  _____  __
   / /   /  _/ ____/ ____/ __ \\/   \\ \\/ /
  / /    / // /_  / __/ / /_/ / /| |\\  /
 / /____/ // __/ / /___/ _, _/ ___ |/ /
/_____/___/_/   /_____/_/ |_/_/  |_/_/
`);

    await this.ask([
      {
        type: 'input',
        name: PROJECT_NAME_VAR,
        message: 'Project name',
        default: 'Sample Liferay Fragments',
      },
      {
        type: 'confirm',
        name: ADD_SAMPLE_CONTENT_VAR,
        message: 'Add sample content?',
        default: true,
      },
    ]);

    this.setDefaultValue(
      PROJECT_SLUG_VAR,
      voca.slugify(this.getValue(PROJECT_NAME_VAR))
    );

    this.throwRequiredError(PROJECT_SLUG_VAR);

    this.destinationRoot(
      this.destinationPath(this.getValue(PROJECT_SLUG_VAR) || '')
    );
  }

  writing(): void {
    this.log('Creating directory', { newLine: true });

    this.copyFiles(this.destinationRoot(), ['src/.gitkeep']);

    this.copyTemplates(this.destinationRoot(), [
      '.editorconfig',
      '.gitignore',
      '.yo-rc.json',
      'liferay-npm-bundler.config.js',
      'package.json',
      'README.md',
    ]);
  }

  async end(): Promise<void> {
    this.log('Running npm install...', { newLine: true });

    if (process.env.NODE_ENV !== 'test') {
      await execa.command('npm install', {
        cwd: this.destinationRoot(),
      });
    }

    if (this.getValue(ADD_SAMPLE_CONTENT_VAR)) {
      this.log('Adding sample content...', { newLine: true });

      this.composeWith(
        {
          Generator: CollectionGenerator,
          path: require.resolve('../collection'),
        },
        {
          [COLLECTION_NAME_VAR]: 'Sample collection',
          [COLLECTION_DESCRIPTION_VAR]: 'Sample collection autogenerated',

          [FRAGMENT_NAME_VAR]: 'Sample fragment',
          [FRAGMENT_TYPE_VAR]: 'component',
          [FRAGMENT_COLLECTION_SLUG_VAR]: 'sample-collection',
          [USE_DATA_LFR_EDITABLES_VAR]: false,
        }
      );

      this.composeWith(
        {
          Generator: CollectionGenerator,
          path: require.resolve('../collection'),
        },
        {
          [COLLECTION_NAME_VAR]: 'Sample collection',
          [COLLECTION_DESCRIPTION_VAR]: 'Sample collection autogenerated',

          [FRAGMENT_NAME_VAR]: 'Sample fragment with new editables',
          [FRAGMENT_TYPE_VAR]: 'component',
          [FRAGMENT_COLLECTION_SLUG_VAR]: 'sample-collection',
          [USE_DATA_LFR_EDITABLES_VAR]: true,
        }
      );

      this.composeWith(
        {
          Generator: CollectionGenerator,
          path: require.resolve('../collection'),
        },
        {
          [COLLECTION_NAME_VAR]: 'Sample collection',
          [COLLECTION_DESCRIPTION_VAR]: 'Sample collection autogenerated',

          [FRAGMENT_NAME_VAR]: 'Sample fragment with react',
          [FRAGMENT_TYPE_VAR]: 'react',
          [FRAGMENT_COLLECTION_SLUG_VAR]: 'sample-collection',
          [USE_DATA_LFR_EDITABLES_VAR]: true,
        }
      );
    }

    setTimeout(() => {
      this.log('Done!', { newLine: true, level: 'success' });
      this.log("You're ready to create fragments.");
    }, 1000);
  }
}
