const ADD_SAMPLE_CONTENT_DEFAULT = true;
const ADD_SAMPLE_CONTENT_MESSAGE = 'Add sample content?';
const ADD_SAMPLE_CONTENT_VAR = 'addSampleContent';

const COLLECTION_DESCRIPTION_VAR = 'collectionDescription';
const COLLECTION_DESCRIPTION_MESSAGE = 'Collection description (optional)';

const COLLECTION_DESCRIPTION_DEFAULT = '';
const COLLECTION_NAME_MESSAGE = 'Collection name';
const COLLECTION_NAME_SAMPLE = 'Sample collection';
const COLLECTION_NAME_VAR = 'collectionName';

const COLLECTION_SLUG_SAMPLE = 'sample-collection';
const COLLECTION_SLUG_VAR = 'collectionSlug';

const FRAGMENT_DESCRIPTION_MESSAGE = 'Fragment description (optional)';
const FRAGMENT_DESCRIPTION_VAR = 'fragmentDescription';

const FRAGMENT_NAME_MESSAGE = 'Fragment name';
const FRAGMENT_NAME_SAMPLE = 'Sample fragment';
const FRAGMENT_NAME_VAR = 'fragmentName';

const FRAGMENT_SLUG_VAR = 'fragmentSlug';

const REPOSITORY_NAME_DEFAULT = 'Sample Liferay Fragments';
const REPOSITORY_NAME_MESSAGE = 'Repository name';
const REPOSITORY_NAME_VAR = 'repositoryName';

const REPOSITORY_SLUG_VAR = 'repositorySlug';

module.exports = {
  ADD_SAMPLE_CONTENT_DEFAULT,
  ADD_SAMPLE_CONTENT_MESSAGE,
  ADD_SAMPLE_CONTENT_VAR,
  COLLECTION_DESCRIPTION_VAR,
  COLLECTION_DESCRIPTION_MESSAGE,
  COLLECTION_DESCRIPTION_DEFAULT,
  COLLECTION_NAME_MESSAGE,
  COLLECTION_NAME_SAMPLE,
  COLLECTION_NAME_VAR,
  COLLECTION_SLUG_SAMPLE,
  COLLECTION_SLUG_VAR,
  FRAGMENT_DESCRIPTION_MESSAGE,
  FRAGMENT_DESCRIPTION_VAR,
  FRAGMENT_NAME_MESSAGE,
  FRAGMENT_NAME_SAMPLE,
  FRAGMENT_NAME_VAR,
  FRAGMENT_SLUG_VAR,
  REPOSITORY_NAME_DEFAULT,
  REPOSITORY_NAME_MESSAGE,
  REPOSITORY_NAME_VAR,
  REPOSITORY_SLUG_VAR
};
