module.exports.ADD_DEPLOYMENT_DESCRIPTOR_DEFAULT = true;
module.exports.ADD_DEPLOYMENT_DESCRIPTOR_MESSAGE = 'Add deployment descriptor?';
module.exports.ADD_DEPLOYMENT_DESCRIPTOR_VAR = 'addDeploymentDescriptor';

module.exports.ADD_SAMPLE_CONTENT_DEFAULT = true;
module.exports.ADD_SAMPLE_CONTENT_MESSAGE = 'Add sample content?';
module.exports.ADD_SAMPLE_CONTENT_VAR = 'addSampleContent';

module.exports.COLLECTION_DESCRIPTION_DEFAULT = '';
module.exports.COLLECTION_DESCRIPTION_MESSAGE =
  'Collection description (optional)';
module.exports.COLLECTION_DESCRIPTION_SAMPLE =
  'Sample collection autogenerated';
module.exports.COLLECTION_DESCRIPTION_VAR = 'collectionDescription';

module.exports.COLLECTION_NAME_MESSAGE = 'Collection name (required)';
module.exports.COLLECTION_NAME_NON_EMPTY_ERROR_MESSAGE =
  'Collection name must not be empty';
module.exports.COLLECTION_NAME_SAMPLE = 'Sample collection';
module.exports.COLLECTION_NAME_VAR = 'collectionName';

module.exports.COLLECTION_SLUG_SAMPLE = 'sample-collection';
module.exports.COLLECTION_SLUG_VAR = 'collectionSlug';

module.exports.DEPLOYMENT_DESCRIPTOR_COMPANY_DEFAULT = 'liferay.com';
module.exports.DEPLOYMENT_DESCRIPTOR_COMPANY_MESSAGE =
  'Deployment descriptor company Web ID?';
module.exports.DEPLOYMENT_DESCRIPTOR_COMPANY_VAR = 'companyWebId';

module.exports.DEPLOYMENT_DESCRIPTOR_GROUP_DEFAULT = 'Guest';
module.exports.DEPLOYMENT_DESCRIPTOR_GROUP_MESSAGE =
  'Deployment descriptor group key?';
module.exports.DEPLOYMENT_DESCRIPTOR_GROUP_VAR = 'groupKey';

module.exports.FRAGMENT_COLLECTION_SLUG_MESSAGE = 'Choose a collection';
module.exports.FRAGMENT_COLLECTION_SLUG_VAR = 'fragmentCollectionSlug';

module.exports.FRAGMENT_NAME_MESSAGE = 'Fragment name (required)';
module.exports.FRAGMENT_NAME_NON_EMPTY_ERROR_MESSAGE =
  'Fragment name must not be empty';
module.exports.FRAGMENT_NAME_SAMPLE = 'Sample fragment';
module.exports.FRAGMENT_NAME_VAR = 'fragmentName';

module.exports.FRAGMENT_COMPOSITION_NAME_MESSAGE =
  'Fragment composition name (required)';
module.exports.FRAGMENT_COMPOSITION_NAME_NON_EMPTY_ERROR_MESSAGE =
  'Fragment name must not be empty';
module.exports.FRAGMENT_COMPOSITION_NAME_SAMPLE = 'Sample fragment composition';
module.exports.FRAGMENT_COMPOSITION_NAME_VAR = 'fragmentCompositionName';

module.exports.FRAGMENT_SLUG_VAR = 'fragmentSlug';

module.exports.FRAGMENT_TYPE_DEFAULT = 'section';
module.exports.FRAGMENT_TYPE_MESSAGE = 'Fragment type';
module.exports.FRAGMENT_TYPE_OPTIONS = [
  { name: 'Section', value: 'section' },
  { name: 'Component', value: 'component' }
];
module.exports.FRAGMENT_TYPE_VAR = 'fragmentType';

module.exports.FRAGMENTS_PORTLET_ID =
  'com_liferay_fragment_web_portlet_FragmentPortlet';

module.exports.IMPORT_WATCH_VAR = 'watch';

module.exports.LIFERAY_COMPANYID_MESSAGE = 'Company ID';
module.exports.LIFERAY_COMPANYID_VAR = 'companyId';

module.exports.LIFERAY_GROUPID_MESSAGE = 'Group ID';
module.exports.LIFERAY_GROUPID_VAR = 'groupId';

module.exports.LIFERAY_HOST_DEFAULT = 'http://localhost:8080';
module.exports.LIFERAY_HOST_MESSAGE = 'Liferay host & port';
module.exports.LIFERAY_HOST_VAR = 'host';

module.exports.LIFERAY_PASSWORD_DEFAULT = 'test';
module.exports.LIFERAY_PASSWORD_MESSAGE = 'Password';
module.exports.LIFERAY_PASSWORD_VAR = 'password';

module.exports.LIFERAY_USERNAME_DEFAULT = 'test@liferay.com';
module.exports.LIFERAY_USERNAME_MESSAGE = 'Username';
module.exports.LIFERAY_USERNAME_VAR = 'username';

module.exports.NEW_COLLECTION_MESSAGE = '+ New collection';
module.exports.NEW_COLLECTION_SHORT = '(new)';
module.exports.NEW_COLLECTION_VALUE = '__NEW_COLLECTION_VALUE__';

module.exports.PORTLET_FILE_REPOSITORY =
  'com.liferay.portal.repository.portletrepository.PortletRepository';

module.exports.PROJECT_NAME_DEFAULT = 'Sample Liferay Fragments';
module.exports.PROJECT_NAME_MESSAGE = 'Project name';
module.exports.PROJECT_NAME_VAR = 'projectName';

module.exports.PROJECT_SLUG_VAR = 'projectSlug';
