name: Check Pull Request

on:
  pull_request:
    branches:
      - master

env:
  CI: true
  yarn-cache-name: yarn-cache-1
  yarn-cache-path: .yarn

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1

  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ 10 ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Use or update Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ env.yarn-cache-path }}
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.yarn-cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --cache-folder=${{ env.yarn-cache-path }} install --frozen-lockfile
      - run: yarn --cache-folder=${{ env.yarn-cache-path }} run lint

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ 10 ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Use or update Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ env.yarn-cache-path }}
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.yarn-cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --cache-folder=${{ env.yarn-cache-path }} install --frozen-lockfile
      - run: yarn --cache-folder=${{ env.yarn-cache-path }} run build

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10, 12, 14]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Use or update Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ env.yarn-cache-path }}
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.yarn-cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --cache-folder=${{ env.yarn-cache-path }} install --frozen-lockfile
      - run: yarn --cache-folder=${{ env.yarn-cache-path }} run test
